name: build-app

on: [pull_request]

jobs:
  build-app:
    runs-on: ubuntu-latest
    env:
      SKIP_PREFLIGHT_CHECK: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Build app
        run: |
          yarn set version 3.0.0
          yarn install
          yarn build
