name: build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SKIP_PREFLIGHT_CHECK: true

    steps:
      - uses: actions/checkout@v2
      - name: Run linter
        run: |
          yarn install
          yarn build
