name: build-storybook

on: [pull_request]

jobs:
  build-storybook:
    runs-on: ubuntu-latest
    env:
      SKIP_PREFLIGHT_CHECK: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: ".node-version": "16"
          cache: "yarn"
      - name: Build app
        run: |
          yarn install
          yarn build-storybook
