name: e2e

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SKIP_PREFLIGHT_CHECK: true
      TZ: Asia/Tokyo

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: 'yarn'
      - name: Prepare package dependencies
        run: |
          yarn install
          yarn codegen
          cp .env.sample .env
      - name: Prepare cypress
        working-directory: ./e2e
        run: yarn install
      - name: Run e2e test
        run: yarn cypress:ci
