name: test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SKIP_PREFLIGHT_CHECK: true
      TZ: Asia/Tokyo

    steps:
      - uses: actions/checkout@v2
      - name: e2e test
        run: |
          yarn install
          cd ./e2e && yarn install && cd ../
          yarn cypress:ci
