name: lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      SKIP_PREFLIGHT_CHECK: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - name: Run linter
        run: |
          yarn install
          yarn lint
