name: test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SKIP_PREFLIGHT_CHECK: true
      TZ: Asia/Tokyo

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "yarn"
      - name: Test components
        run: |
          yarn install
          yarn test
