name: test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SKIP_PREFLIGHT_CHECK: true

    steps:
      - uses: actions/checkout@v2
      - name: Test components
        run: |
          yarn install
          yarn test
